name: NodeCI

on: [pull_request, push]

jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup NodeJS 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
